### ISSUE TITLE
Having issues creating terraform instance

### ISSUE THREAD

**Issue by parima08** [jdtriska/instant-jellyfin#5]
Hi there!

Thanks for creating such a wonderful guide! I'm having issues actually deploying the instance to AWS. I keep hitting these errors. Could you help point me in the right direction? Also - where would I be able to find the domain of where this instance is running? 

Thanks!
```

20:07 $ docker-compose -f docker-compose.terraform.apply.yml up --build
Building terraform
Step 1/2 : FROM hashicorp/terraform:0.12.23
 ---> 04c08ada2f77
Step 2/2 : WORKDIR /instant-jellyfin
 ---> Using cache
 ---> 5b8c7c73f298

Successfully built 5b8c7c73f298
Successfully tagged instant-jellyfin_terraform:latest
Recreating instant-jellyfin_terraform_1 ... done
Attaching to instant-jellyfin_terraform_1
terraform_1  | aws_key_pair.jellyfin_keys: Creating...
terraform_1  | aws_vpc.jellyfin_vpc: Creating...
terraform_1  |
terraform_1  | Error: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'jellyfin-key' already exists.
terraform_1  | 	status code: 400, request id: ba82848b-b8f4-4541-932c-d484b64b7d03
terraform_1  |
terraform_1  |   on jellyfin.tf line 200, in resource "aws_key_pair" "jellyfin_keys":
terraform_1  |  200: resource "aws_key_pair" "jellyfin_keys" {
terraform_1  |
terraform_1  |
terraform_1  |
terraform_1  | Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
terraform_1  | 	status code: 400, request id: e7f9b515-ab59-47cd-b280-1abcce2afbc1
terraform_1  |
terraform_1  |   on jellyfin.tf line 354, in resource "aws_vpc" "jellyfin_vpc":
terraform_1  |  354: resource "aws_vpc" "jellyfin_vpc" {
terraform_1  |
terraform_1  |
instant-jellyfin_terraform_1 exited with code 1
```

**Comment by jdtriska** [comment]
Hey there, I can absolutely try! First a question: Is this being set up from scratch, or have you gone through the terraform plan/apply cycle a few times already?

Judging by the errors, there are two things going on:

**1. Duplicate key pair**
It looks like for the first you're getting an `InvalidKeyPair.Duplicate` error. This indicates that the given key pair already exists on AWS. This could mean that you're trying to upload a key pair that has already been uploaded, but isn't in your terraform state (it's trying to create something that already exists). This could happen if you have already uploaded the key pair to AWS manually outside of terraform, or you deleted your terraform state and are trying again without having cleaned out the resources it had created on AWS.

There are two solutions here:
1. If you didn't manually upload that key pair, and you don't need it, just delete it manually by visiting the [AWS EC2 console](https://console.aws.amazon.com/ec2/v2/home) and selecting **Key Pairs.**
2. You could use [Terraform import](https://www.terraform.io/docs/import/usage.html) to add the existing key pair to your state. I would only recommend this if you need to keep the existing key pair for some reason.

**2. Exceeded VPC limit**
This happens when you have more VPCs created already than AWS allows. I believe the limit is 5 by default.

I think what may have happened here--just a guess assuming you're setting this project up for the first time--is that you may have run Terraform init/plan/apply cycle once, then completely started from scratch again, and told terraform to start with a fresh state when you ran the `init` step again. This will wipe out your state, which keeps track of what Terraform has created on AWS, but leave anything that it has already create alone, so there will be a bunch of resources that it created but doesn't remember. If this happened multiple times, you could easily end up with 5 duplicate VPCs that you don't need. This would also explain the duplicate key pair.

You should take a look at your [AWS console](https://console.aws.amazon.com/) and make sure you don't have any existing resources that could be conflicting with what you're trying to set up. You'll definitely want to check S3, EC2, VPC, and Route53. If this did happen, I would spend a little time reading through the Terraform to see what is created and manually deleting it from the console, then starting fresh.

As far as where you can find the endpoint, Terraform will output this after you successfully apply, OR you can check the AWS console. If you set this up with a custom domain, it should be hosted at that domain (you can check Route53). If you did not use a custom domain, you can check EC2 under **Load balancers** for the endpoint of the application load balancer created by Terraform.

Let me know if this helps, or if you have any other questions.

**Comment by parima08** [comment]
This was great! Got it up and working. Had to manually delete the load balancer, ran it again and got it up and running. 

Thanks for being so detailed in your response back to me. Really appreciate it!

**Comment by jdtriska** [comment]
No problem, glad you got it working.

**Comment by parima08** [comment]
Hi there! Sorry to bother you again- didn't want to create a new issue as this is more of a question than an issue. 

I have my own repo with a custom build of jellyfin that I want to use (with my custom themes and images). Is there a way I can point instant-jellyfin to my repo or a docker-image of jellyfin that I have created? 

Your help is greatly appreciated! Thanks!

**Comment by jdtriska** [comment]
Absolutely, you can modify `~/jellyfin/scripts/start-jellyfin.sh` to pull the image you want. Here's the existing command:
```bash
docker run -d \
 --volume ~/jellyfin/config:/config \
 --volume ~/jellyfin/cache:/cache \
 --volume ~/jellyfin/media:/media \
 --user 1000:1000 \
 --net=host \
 --restart=unless-stopped \
 --name jellyfin \
 jellyfin/jellyfin # <---change out this docker image
```
You could modify this to pull a dockerhub private image (see https://docs.docker.com/docker-hub/repos/#private-repositories), or pull the image from AWS ECR (see https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html).

Authentication might be easier from ECR, since you would just need to modify the Terraform to give the EC2 instance permission to access your ECR repository (modify the `jellyfin_server_policy` resource in `jellyfin.tf` and add the appropriate IAM permission), then authenticate inside the script (see https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth). Then you'd be able to run the image you've pulled instead of the standard Dockerhub jellyfin.

Hope this helps!
